-- Q36.1 Complete this palindrome-testing project so it’s the same as the code in the pre- ceding lesson.
--   Then implement property tests to fully test preprocess, ensuring that whitespace doesn’t matter and
--   that capitalization doesn’t matter.
