-- Q23.1 Rewrite the hello_world.hs program (reproduced here) from lesson 21 to use
--   Text instead of String types.
--
--     helloPerson :: String -> String
--     helloPerson name = "Hello" ++ " " ++ name ++ "!"
--
--     main :: IO ()
--     main = do
--       putStrLn "Hello! What's your name?"
--       name <- getLine
--       let statement = helloPerson name
--       putStrLn statement

-- Q23.2 Use Data.Text.Lazy and Data.Text.Lazy.IO to rewrite the lazy I/O section from lesson
--   22 by using the Text type.
--
--     toInts :: String -> [Int]
--     toInts = map read . lines
--
--     main :: IO ()
--     main = do
--       userInput <- getContents
--       let numbers = toInts userInput
--       print (sum numbers)
