-- Q35.1 Make the following changes to this project:
--   - Set the author, description, and maintainer email to the correct info.
--   - Return the definition of Lib.hs to the original one created by stack.
--   - Add the code for isPalindrome into a Palindrome module in src/Palindrome.hs.
--   - Make sure that OverloadedStrings is set at the project level.
