-- Q35.2 Refactor the code in unit 4, lesson 21, for comparing the cost of two pizzas into a stack project.
--   All of the supporting code in the original program file should be in either Lib.hs or an additional library module.
