-- Q34.1 Recall that in unit 4 we mentioned that Data.Text is strongly preferred over String for working with text data.
--   Refactor this project to use Data.Text instead of String (in both the Main and Palindrome modules).
