-- Q10.3 Create a list of three robots.
--   Then create a fourth robot.
--   Use partial application to create a closure for the fight method so
--   the fourth robot can fight all three robots at once, using map.
--   Finally, use map to get the remaining life from the rest of the robots.
