-- Q42.2 Write a function that takes a UArray Int Int as an input.
--   The input will have a mixture of zeros and other values.
--   The function, replaceZeros, should return the array with all of the zeros replaced with the value –1.
